# Generated by Django 5.2 on 2025-05-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_comment_created_at_comment_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
