# .github/workflows/test-deploy.yml
name: Test and Deploy

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Run tests on test VM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: SSH to Test Server and Run Tests
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -rf final-repo
            git clone https://github.com/KaworuMB/final-repo.git
            cd final-repo/final-project-inf373
            docker-compose down -v --remove-orphans || true
            docker-compose up -d --build
            sleep 20  # wait for services to boot
            docker-compose exec web python manage.py test || exit 1
            docker-compose down -v --remove-orphans

  deploy:
    name: Deploy to production VM
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -rf final-repo
            git clone https://github.com/KaworuMB/final-repo.git
            cd final-repo/final-project-inf373
            docker-compose down -v --remove-orphans || true
            docker-compose up -d --build
